from enum import Enum

catalog = dict()

class spell:
    def __init__(self, genRole, genSchool, genDuration, genCastTime, genRange, genSize, genShape, genComponents, genDescription):
        self.role = genRole
        self.school = genSchool
        self.duration = genDuration
        self.castTime = genCastTime
        self.range = genRange
        self.size = genSize
        self.shape = genShape
        self.components = genComponents
        self.description = genDescription

    class Shape(Enum):
        NONE = 1
        LINE = 2
        CONE = 3
        CUBE = 4
        SPHERE = 5
        CYLINDER = 6

#Cantrips

catalog["Acid Splash"] = spell(["Sorceror", "Wizard", "Artificer"], "Conjuration", "Instantaneous", "1 Action", 60, 0, spell.Shape.NONE, ['V', 'S'], "You hurl a bubble of acid. Choose one or two creatures you can see within range. If you choose two, they must be within 5 feet of each other. A target must succeed on a Dexterity saving throw or take 1d6 acid damage. \nThis spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).")
catalog["Blade Ward"] = spell(["Bard", "Sorceror", "Warlock", "Wizard"], "Abjuration", "1 Round","1 Action" ,0, 0, spell.Shape.NONE , ['V', 'S'], "You extend your hand and trace a sigil of warding in the air. Until the end of your next turn, you have resistance against bludgeoning, piercing, and slashing damage dealt by weapon attacks.")
catalog["Chill Touch"] = spell(["Sorceror", "Warlock", "Wizard"], "Necromancy", "1 Minute","1 Action" ,120, 0, spell.Shape.NONE, ['V', 'S'], "You extend your hand and trace a sigil of warding in the air. Until the end of your next turn, you have resistance against bludgeoning, piercing, and slashing damage dealt by weapon attacks. \nIf you hit an undead target, it also has disadvantage on attack rolls against you until the end of your next turn.\nThis spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).")
catalog["Control Flames"] = spell(["Druid", "Sorceror", "Wizard"], "Transmutation","Instantaneous" ,"1 Action" ,60, 5, spell.Shape.CUBE, ['S'], "You choose nonmagical flame that you can see within range and that fits within a 5-foot cube. You affect it in one of the following ways: \n\n\tYou instantaneously expand the flame 5 feet in one direction, provided that wood or other fuel is present in the new location.\n\n\tYou instantaneously extinguish the flames within the cube.\n\n\tYou double or halve the area of bright light and dim light cast by the flame, change its color, or both. The change lasts for 1 hour.\n\n\tYou cause simple shapes—such as the vague form of a creature, an inanimate object, or a location—to appear within the flames and animate as you like. The shapes last for 1 hour.\n\nIf you cast this spell multiple times, you can have up to three of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.")
catalog["Create Bonfire"] = spell(["Druid", "Sorceror", "Warlock", "Wizard", "Artificer"], "Conjuration","1 Minute" , "1 Action",60 , 5, spell.Shape.CUBE, ['V', 'S'], "You create a bonfire on ground that you can see within range. Until the spell ends, the magic bonfire fills a 5-foot cube. Any creature in the bonfire’s space when you cast the spell must succeed on a Dexterity saving throw or take 1d8 fire damage. A creature must also make the saving throw when it moves into the bonfire’s space for the first time on a turn or ends its turn there.\n\nThe bonfire ignites flammable objects in its area that aren’t being worn or carried.\n\nThe spell’s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).")
catalog["Dancing Lights"] = spell(["Bard", "Sorceror", "Wizard", "Artificer"], "Evocation","1 Minute" ,"1 Action", 120, 0, spell.Shape.NONE, ['V, S, M'], "You create up to four torch-sized lights within range, making them appear as torches, lanterns, or glowing orbs that hover in the air for the duration. You can also combine the four lights into one glowing vaguely humanoid form of Medium size. Whichever form you choose, each light sheds dim light in a 10-foot radius.\n\nAs a bonus action on your turn, you can move the lights up to 60 feet to a new spot within range. A light must be within 20 feet of another light created by this spell, and a light winks out if it exceeds the spell's range.\n\nMaterials: a bit of phosphorus or wychwood, or a glowworm")
catalog["Druidcraft"] = spell(["Druid"], "Transmutation", "Instantaneous", "1 Action", 30, 0, spell.Shape.NONE, ['V', 'S'], "Whispering to the spirits of nature, you create one of the following effects within range:\n\n\tYou create a tiny, harmless sensory effect that predicts what the weather will be at your location for the next 24 hours. The effect might manifest as a golden orb for clear skies, a cloud for rain, falling snowflakes for snow, and so on. This effect persists for 1 round.\n\n\tYou instantly make a flower blossom, a seed pod open, or a leaf bud bloom.\n\n\tYou create an instantaneous, harmless sensory effect, such as falling leaves, a puff of wind, the sound of a small animal, or the faint odor of skunk. The effect must fit in a 5-foot cube.\n\n\tYou instantly light or snuff out a candle, a torch, or a small campfire.")
catalog["Eldritch Blast"] = spell(["Warlock"], "Evocation", "Instantaenous", "1 Action", 120, 0, spell.Shape.NONE, ['V', 'S'], "A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 force damage.\n\nThe spell creates more than one beam when you reach higher levels: two beams at 5th level, three beams at 11th level, and four beams at 17th level. You can direct the beams at the same target or at different ones. Make a separate attack roll for each beam.")
catalog["Fire Bolt"] = spell(["Sorceror", "Wizard", "Artificer"], "Evocation", "Instantanetous", "1 Action", 120, 0, spell.Shape.NONE, ['V', 'S'], "You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn't being worn or carried.\n\nThis spell's damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).")
catalog["Friends"] = spell(["Bard", "Sorceror", "Warlock", "Wizard"], "Enchantment", "1 Minute", "1 Action", 0, 0, spell.Shape.NONE, ['S', 'M'], "For the duration, you have advantage on all Charisma checks directed at one creature of your choice that isn’t hostile toward you. When the spell ends, the creature realizes that you used magic to influence its mood and becomes hostile toward you. A creature prone to violence might attack you. Another creature might seek retribution in other ways (at the DM’s discretion), depending on the nature of your interaction with it.\n\nMaterials: a small amount of makeup applied to the face as this spell is cast")
catalog["FrostBite"] = spell(["Druid", "Sorceror", "Warlock", "Wizard", "Artificer"], "Evocation", "Instantaneous", "1 Action", 60, 0, spell.Shape.NONE, ['V', 'S'], "You cause numbing frost to form on one creature that you can see within range. The target must make a Constitution saving throw. On a failed save, the target takes 1d6 cold damage, and it has disadvantage on the next weapon attack roll it makes before the end of its next turn.\n\nThe spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).")
catalog["Guidance"] = spell(["Cleric", "Druid", "Artificer"], "Divination", "1 Minute", "1 Action", 0, 0, spell.Shape.NONE, ['V', 'S'], "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends.")
catalog["Gust"] = spell(["Druid", "Sorceror", "Wizard"], "Transmutation", "Instantaneous", "1 Action", 30, 0, spell.Shape.NONE, ['V', 'S'], "You seize the air and compel it to create one of the following effects at a point you can see within range:\n\n\tOne Medium or smaller creature that you choose must succeed on a Strength saving throw or be pushed up to 5 feet away from you.\n\n\tYou create a small blast of air capable of moving one object that is neither held nor carried and that weighs no more than 5 pounds. The object is pushed up to 10 feet away from you. It isn’t pushed with enough force to cause damage.\n\n\tYou create a harmless sensory effect using air, such as causing leaves to rustle, wind to slam shutters shut, or your clothing to ripple in a breeze.")
catalog["Light"] = spell(["Bard", "Cleric", "Sorceror", "Wizard", "Artificer"], "Evocation", "1 Hour", "1 Action", 0, 20, spell.Shape.CUBE, ['V', 'M'], "You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light in a 20-foot radius and dim light for an additional 20 feet. The light can be colored as you like. Completely covering the object with something opaque blocks the light. The spell ends if you cast it again or dismiss it as an action.\n\nIf you target an object held or worn by a hostile creature, that creature must succeed on a Dexterity saving throw to avoid the spell.\n\nMaterials: a firefly of phosphorescent moss")
catalog["Mage Hand"] = spell(["Bard", "Sorceror", "Warlock", "Wizard", "Artificer"], "Conjuration", "1 Minute", "1 Action", 30, 0, spell.Shape.NONE, ['V', 'S'], "A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it as an action. The hand vanishes if it is ever more than 30 feet away from you or if you cast this spell again.\n\nYou can use your action to control the hand. You can use the hand to manipulate an object, open an unlocked door or container, stow or retrieve an item from an open container, or pour the contents out of a vial. You can move the hand up to 30 feet each time you use it.\n\nThe hand can't attack, activate magic items, or carry more than 10 pounds.")

